name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t propert-ease:1.0 . && docker run -dit --name propert-ease-container -p 8080:80 -p 13331:13331 propert-ease:1.0
    - name: Setup Pages
      uses: actions/configure-pages@v4.0.0
      with:
        token: ${{ github.token }}
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3.0.0
      with:
        name: github-pages
        path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    steps:
    - name: Deploy GitHub Pages site
      id: deployment
      uses: actions/deploy-pages@v4.0.3
      with:
        token: ${{ github.token }}
        artifact_name: github-pages
          
